# Generated by Django 4.2.14 on 2024-08-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_buyer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
