# Generated by Django 4.2.14 on 2024-09-01 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_buyer_login_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='LOGIN_ID',
        ),
        migrations.AddField(
            model_name='buyer',
            name='LOGIN_ID_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.login'),
        ),
    ]
