# Generated by Django 4.2.14 on 2024-09-01 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_buyer_login_id_buyer_login_id_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='LOGIN_ID_id',
            new_name='LOGIN_ID',
        ),
    ]
