# Generated by Django 4.2.14 on 2024-09-01 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_login_id_id_buyer_login_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='LOGIN_ID',
        ),
    ]
