# Generated by Django 4.2.14 on 2024-09-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_login_login_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='district',
            new_name='county',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='pin',
        ),
        migrations.AddField(
            model_name='buyer',
            name='town',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='post',
            field=models.CharField(max_length=50),
        ),
    ]
