# Generated by Django 4.2.14 on 2024-09-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_district_buyer_county_remove_buyer_pin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
