# Generated by Django 4.2.14 on 2024-09-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_login_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='house_no_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='place',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='post',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
