# Generated by Django 4.2.14 on 2024-09-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_buyer_house_no_name_alter_buyer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='county',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='town',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
