# Generated by Django 4.2.14 on 2024-09-09 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_buyer_county_alter_buyer_town'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='login',
            name='usertype',
        ),
    ]
