# Generated by Django 4.2.14 on 2024-09-26 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='PRODUCT_CATEGORY',
            new_name='category',
        ),
    ]
