# Generated by Django 4.2.14 on 2024-10-03 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_rename_category_product_categroy_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='CATEGROY_ID',
            new_name='CATEGORY_ID',
        ),
    ]
