# Generated by Django 4.2.14 on 2024-10-03 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_rename_categroy_id_product_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='CATEGORY_ID',
            new_name='CATEGORY_NAME',
        ),
    ]
