# Generated by Django 4.2.14 on 2024-10-03 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_rename_category_id_product_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='CATEGORY_NAME',
            new_name='CATEGORY_ID',
        ),
    ]
