# Generated by Django 4.2.14 on 2024-10-07 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='BUYER_ID',
        ),
        migrations.AddField(
            model_name='cart',
            name='LOGIN_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.login'),
            preserve_default=False,
        ),
    ]
