# Generated by Django 4.2.14 on 2024-10-14 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_remove_cart_login_id_cart_buyer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='house_no_name',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='name',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='place',
            new_name='f_name',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='post',
            new_name='l_name',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='county',
        ),
        migrations.AddField(
            model_name='buyer',
            name='zipcode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Shipping_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50, null=True)),
                ('l_name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('town', models.CharField(max_length=50, null=True)),
                ('zipcode', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('LOGIN_ID', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
    ]
