# Generated by Django 4.2.14 on 2024-10-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_rename_house_no_name_buyer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_amt',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
