# Generated by Django 4.2.14 on 2024-10-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_cart_total_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_amt',
            field=models.FloatField(max_length=50),
        ),
    ]
